[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"
[context.production]
  [context.production.environment]
    FRONT_API_URL="https://romantic-hugle-ee30ac.netlify.com/.netlify/functions"
