[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"
[context.production]
  [context.production.environment]
    FRONT_API_URL="https://quirky-ride-1af1f5.netlify.com/.netlify/functions"
